package net.yura.domination.engine.core;

public enum GameState {
	STATE_NEW_GAME
	,STATE_TRADE_CARDS
	,STATE_PLACE_ARMIES
	,STATE_ATTACKING
	,STATE_ROLLING
	,STATE_BATTLE_WON
	,STATE_FORTIFYING
	,STATE_END_TURN
	,STATE_GAME_OVER
	,STATE_SELECT_CAPITAL
	,STATE_DEFEND_YOURSELF
}
